# Page settings
baseurl = "http://pgdpiept.designedu.pt/"
title = "PGDPIE"
languageCode = "pt-pt"
theme = "pgdpie_theme"


[params]
  
  custom_css = ["css/custom1.css", "css/custom2.css"]

  googleFonts = "https://fonts.googleapis.com/css2?family=PT+Sans+Caption:wght@400;700&family=PT+Sans:ital,wght@0,400;0,700;1,400;1,700&display=swap"

  # Meta
  author = "Coordenação PGDPIE"
  description = ""
  email = ""

  # Google Maps Javascript API Key (if not set will default to not passing a key)
  googleMapsApiKey = ""

  # Navigation
  [params.navigation]
    brand = "images/logoPT.svg"
    home = "Home"
    services = "Sobre"
    work = "Projetos 2022-23"
    about = "Equipa"
    testimonials = "Testemunhos"
    contact = "Contactos"
    EN = "EN"
  

    # You can add custom links before or after the default links
    # Assign a weight to define the order
    
    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    [[menu.postpend]]
      url = "https://pgdpie.designedu.pt"
      name = "EN"
      weight = 10
  
  # Hero section
  [params.hero]
    title = "A Pós-Graduação em Design de Produtos Interativos para Educação"
    subtitle = "capacita profissionais de design e educação para uma integração perfeita em equipas multidisciplinares, com foco no design, seleção e implementação de produtos interativos para educação em diversos domínios, incluindo brinquedos, recursos educacionais abertos, gráficos interativos e prototipagem em Fablab."
  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "Olá! Designer?"
    description = "Amplie a sua experiência em design para educação, de modo a integrar equipas multidisplinares na área"
    # url = "#about"
    # button = "Know More"
    icon = "icon-bulb"
    img = "img_7.jpg"

  [[params.intro.item]]
    title = "Professor? Educador?"
    description = "Desbloqueie novas possibilidades no design para educação ao aperfeiçoar as suas competências na seleção e implementação de produtos interativos para educação através do nosso programa de pós-graduação especializado."
    # url = "#about"
    # button = "Click Me"
    icon = "icon-wrench"
    img = "img_8.jpg"

  [[params.intro.item]]
    title = "Outros Profissionais de Educação ou Design?"
    description = "Expanda os seus horizontes e impulsione a sua carreira adquirindo competências avançadas em design, seleção e implementação de produtos interativos para educação."
    # url = "#about"
    # button = "Why us?"
    icon = "icon-rocket"
    img = "img_10.jpg"

  [params.intro.video]
    enable = false
    title = "Watch the video"
    icon = "icon-play2"
    url = "https://vimeo.com/channels/staffpicks/93951774"

    
  # Services section
  [params.services]
    enable = true
    title = "Sobre o Curso:"
    description = "A PGDPIE assenta num plano de estudos que privilegia uma definição abrangente e inclusiva do que pode ser um produto interativo. Assim, da app ao brinquedo, do digital ao tangível, todas as abordagens terão lugar neste curso. Assim, o curso prevê a realização de um projeto final, avaliado através da UC de Projeto de Produtos Interativos para Educação, no entanto, formulado desenvolvido acompanhado nas diferentes UC’s de acordo com as temáticas e ferramentas que privilegiarão. Por fim, a interação com o Fablab Benfica, enquanto espaço de prototipagem será uma constante ao longo do curso."
    subtitle = "Plano de Estudos:"
    description2 = "A Pós-graduação em Design de Produtos Interativos para Educação é um curso, com um total de 60 ECTS e a duração de 2 semestres, que visa o aprofundamento de competências em design e prototipagem para a área educativa, servindo profissionais tanto da área da educação como da área do design, que pretendam desenvolver produtos ou projetos dentro da sua instituição ou mesmo abraçar novas oportunidades na área dos produtos interativos para educação."
  
    subtitle3 = "Objetivos"
    description3 = ""
    subtitle4 = "Plano de Estudos:"
    description4 = "A Pós-graduação em Design de Produtos Interativos para Educação é um curso, com um total de 60 ECTS e a duração de 2 semestres, que visa o aprofundamento de competências em design e prototipagem para a área educativa, servindo profissionais tanto da área da educação como da área do design, que pretendam desenvolver produtos ou projetos dentro da sua instituição ou mesmo abraçar novas oportunidades na área dos produtos interativos para educação."

    [[params.services.item]]
      title = "Objectivos"
      description = ""
      icon = "icon-anchor"

    [[params.services.item]]
      title = "Educations &amp; Interface"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
      icon = "icon-layers2"
    [[params.services.item]]
      title = "Photo &amp; Video"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
      icon = "icon-video2"

      [[params.services.item]]
      title = "CMS &amp; eCommerce"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"      
      icon = "icon-monitor"

  # About section
  [params.about]
    enable = true
    title = "Equipa"
    description = "Conheça a nossa equipa de Professores"

    [[params.about.item]]
      name = "Luís Frias"
      position = "Professor"
      description = ""
      img = "lf.jpg"
      alt = "Luís Frias"
      social = [
      #  ["icon-twitter", "#"],
      #  ["icon-facebook", "#"],
         ["icon-linkedin", "http://www.linkedin.com/in/luisfriasdesign"]
      ]

    [[params.about.item]]
      name = "Bernardo Gaeiras"
      position = "Professor"
      description = ""
      img = "bg.jpg"
      alt = "Bernardo Gaeiras"
      social = [
      #  ["icon-twitter", "#"],
      #  ["icon-facebook", "#"],
         ["icon-linkedin", "https://www.linkedin.com/in/bernardo-gaeiras/"]
      ]

    [[params.about.item]]
      name = "Madalena Matoso"
      position = "Professora"
      description = ""
      img = "person2.jpg"
      alt = "Madalena Matoso"
      social = [
      #  ["icon-twitter", "#"],
      #  ["icon-facebook", "#"],
         ["icon-linkedin", "#"]
      ]

    [[params.about.item]]
      name = "André Sier"
      position = "Professor"
      description = ""
      img = "as.jpg"
      alt = "André Sier"
      social = [
      #  ["icon-twitter", "#"],
      #  ["icon-facebook", "#"],
         ["icon-wwww", "https://andre-sier.com/"]
      ]

    [[params.about.item]]
      name = "Miguel Mata Pereira"
      position = "Professor"
      description = ""
      img = "mmp.jpg"
      alt = "Miguel Mata Pereira"
      social = [
      #  ["icon-twitter", "#"],
      #  ["icon-facebook", "#"],
        ["icon-linkedin", "https://www.linkedin.com/in/miguel-mata-pereira-28130027a"]
      ]

    [[params.about.item]]
      name = "Miguel Soeiro"
      position = "Professor"
      description = ""
      img = "ms.jpg"
      alt = "Miguel Soeiro"
      social = [
        ["icon-www", "https://miguelsoeiro.com/"],
      #  ["icon-facebook", "#"],
      #  ["icon-github", "#"]
      ]

    [[params.about.item]]
      name = "Pedro Mosca"
      position = "Professor"
      description = ""
      img = "person3.jpg"
      alt = "Person3"
      social = [
      #  ["icon-twitter", "#"],
      # ["icon-facebook", "#"],
      #  ["icon-dribbble", "#"]
      ]

      [[params.about.item]]
      name = "Adriana Cardoso"
      position = " Equipa de Coordenação"
      description = ""
      img = "ac.jpg"
      alt = "Adriana Cardoso"
      social = [
      #  ["icon-linkedin", "https://www.linkedin.com/in/nunomonge"],
      #  ["icon-facebook", "#"],
      #  ["icon-github", "#"]
      ]

      [[params.about.item]]
      name = "Tiago Almeida"
      position = "Equipa de Coordenação"
      description = ""
      img = "person3.jpg"
      alt = "Tiago Almeida"
      social = [
      #  ["icon-linkedin", "https://www.linkedin.com/in/nunomonge"],
      #  ["icon-facebook", "#"],
      #  ["icon-github", "#"]
      ]  

      [[params.about.item]]
      name = "Nuno Monge"
      position = "Equipa de Coordenação"
      description = ""
      img = "nm.jpg"
      alt = "Nuno Monge"
      social = [
        ["icon-linkedin", "https://www.linkedin.com/in/nunomonge"],
      #  ["icon-facebook", "#"],
      #  ["icon-github", "#"]
      ]   

    [[params.about.item]]
      name = "André Rocha"
      position = "Coordenador de Curso"
      description = ""
      img = "ar.jpg"
      alt = "André Rocha"
      social = [
        ["icon-linkedin", "https://www.linkedin.com/in/steam228"],
      #  ["icon-facebook", "#"],
      #  ["icon-github", "#"]
      ]      

  # Counters section
  [params.counters]
    enable = true
    title = "A PGDPIE em números"
    background = "full_image_1.jpg"

    [[params.counters.item]]
      description = "Horas de Contacto"
      icon = "icon-clock"
      from = 0
      to = 360
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "ECTS"
      icon = "icon-briefcase"
      from = 0
      to = 60
      interval = 5
      speed = 3000

      [[params.counters.item]]
      description = "Horas de Projeto Final"
      icon = "icon-pencil"
      from = 0
      to = 120
      interval = 10
      speed = 4000

      [[params.counters.item]]
      description = "Projetos"
      icon = "icon-paper"
      from = 0
      to = 1
      interval = 1
      speed = 500

# Work section
  [params.work]
  enable = true
  title = "Projetos Finais 2022-23"
  description = "O sucesso da nossa primeira edição está expresso na qualidade dos projetos finais e no entusiasmo demonstrado pelo(a)s estudantes nas suas apresentações finais. O catálogo da fabschools ficará mais rico!"
  footertext = 'Os projetos estarão ligados às suas entradas no catálogo fabschools.pt' 

   [[params.work.row]]
  img = "work_1.jpg"
  alt = "Animalgama"
  title = "Animalgama"
  subtitle = "Blocos de construção para aprender sobre animais"
  url = "https://sites.google.com/view/animalgama"

[[params.work.row]]
  img = "work_2.jpg"
  alt = "UP"
  title = "UP - Unidades Precisas"
  subtitle = "Um jogo de sala de aula sobre unidades de medida"
  url = "https://sites.google.com/view/unidades-precisas/"

[[params.work.row]]
  img = "work_3.jpg"
  alt = "GameleonEDU"
  title = "GameleonEDU"
  subtitle = "Uma plataforma que cria jogos para qualquer conteúdo"
  url = "https://gameleonedu.github.io/gameleon.edu/index.html"

[[params.work.row]]
  img = "work_4.jpg"
  alt = "Print out of the Box"
  title = "Print out of the Box"
  subtitle = "Kit pedagógico de gravura"
  url = "https://m.facebook.com/artetransformer"

[[params.work.row]]
  img = "work_5.jpg"
  alt = "Adrinkadeira"
  title = "Adrinkadeira"
  subtitle = "Um jogo para criar histórias e poemas"
  url = "https://sites.google.com/view/adinkradeira"

[[params.work.row]]
  img = "work_6.jpg"
  alt = "Imagem6"
  title = "Chão de Imaginação"
  subtitle = "Tapete origami para crianças"
  url = ""


  # Testimonials section
  [params.testimonials]
    enable = false
    title = "Testimonials"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.&rdquo;"
      person = 'Jean Doe, CEO <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person1.jpg"
      alt = "Person1"

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean. Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.&rdquo;"
      person = 'John Doe, Senior UI <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person2.jpg"
      alt = "Person2"

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. &rdquo;"
      person = 'Chris Nash, Director <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person3.jpg"
      alt = "Person3"

  # Contact section
  [params.contact]
    enable = true
    map = false
    form = true
    title = "Contactos"
    description = ""
    
    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-home", "Campus de Benfica do IPL, 1549-003 Lisboa"],
        ["icon-phone", "+351 217 100 000"],
        ["icon-envelope", ""],
        ["icon-globe", '<a href="http://fabschools.pt" target="_blank">PGDIPE é uma iniciativa fabschools na ESELx/IPL</a>']
      ]

    name = "Nome"
    email = "Email"
    phone = "Telefone"
    message = "Mensagem"
    button = "Enviar mensagem"

  # Footer section
  [params.footer]
    enable = true
    copyright = 'cc-by PGDPIE coordination team at ESELx-IPL'
    links = [
        ["icon-twitter", "https://twitter.com/BenficaFab"],
        ["icon-facebook", "https://www.facebook.com/FabLabBenfica"],
        ["icon-instagram", "https://www.instagram.com/fablab_benfica/"],
        ["icon-youtube", "https://www.youtube.com/channel/UCkjaSC1Vzg8OtVQWADQhCvg"]
      ]
